import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.7";
const sql=postgres(Deno.env.get("SUPABASE_DB_URL")!,{prepare:false,max:1});
const VERSION="1.0.1",PROTOCOL="2025-11-25";
const HDR={"Referer":"https://stock.finance.sina.com.cn/","User-Agent":"Mozilla/5.0"};
let tok:string|null=null,tokAt=0;async function token(){if(tok&&Date.now()-tokAt<300000)return tok;const r=await sql`select decrypted_secret from vault.decrypted_secrets where name='jin10_bearer_token' limit 1`;tok=String(r?.[0]?.decrypted_secret||"");tokAt=Date.now();if(!tok)throw new Error("missing gateway token");return tok}
function jr(id:any,result:any,status=200){return new Response(JSON.stringify({jsonrpc:"2.0",id,result}),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function je(id:any,code:number,message:string,data?:any,status=200){return new Response(JSON.stringify({jsonrpc:"2.0",id:id??null,error:{code,message,...(data===undefined?{}:{data})}}),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function wrap(data:any){return{content:[{type:"text",text:JSON.stringify(data)}],structuredContent:{data,status:200,message:""}}}
function num(x:any){const n=Number(x);return Number.isFinite(n)?n:x}
async function listRaw(param:string){const r=await fetch(`https://hq.sinajs.cn/list=${encodeURIComponent(param)}`,{headers:HDR});if(!r.ok)throw new Error(`Sina HTTP ${r.status}`);const t=new TextDecoder("gbk").decode(await r.arrayBuffer());const m=t.match(/="([\s\S]*?)"/);return m?m[1].split(","):[]}
async function codes(a:any){const underlying=String(a?.underlying||"510050"),call=a?.call!==false;const cate:any={"510050":"50ETF","510300":"300ETF","588000":"科创50ETF","510500":"500ETF"};if(!cate[underlying])throw new Error("underlying must be 510050/510300/588000/510500");const r=await fetch(`https://stock.finance.sina.com.cn/futures/api/openapi.php/StockOptionService.getStockName?exchange=null&cate=${encodeURIComponent(cate[underlying])}`,{headers:HDR});if(!r.ok)throw new Error(`Sina option month HTTP ${r.status}`);const j=await r.json();const months=(j?.result?.data?.contractMonth||[]).slice(1).map((m:string)=>m.replace(/-/g,"").slice(2));const flag=call?"OP_UP_":"OP_DOWN_",out:any={};for(const m of months){const xs=(await listRaw(`${flag}${underlying}${m}`)).filter((x:string)=>x.startsWith("CON_OP_")).map((x:string)=>x.replace("CON_OP_",""));if(xs.length)out[m]=xs}return wrap({source:"sina",underlying,type:call?"call":"put",months:out})}
async function tq(a:any){const code=String(a?.code||"");if(!/^\d+$/.test(code))throw new Error("code required");const v=await listRaw(`CON_OP_${code}`);if(v.length<43)throw new Error("option quote payload too short");return wrap({source:"sina",code,bid_vol:num(v[0]),bid:num(v[1]),last:num(v[2]),ask:num(v[3]),ask_vol:num(v[4]),open_interest:num(v[5]),pct:num(v[6]),strike:num(v[7]),prev_close:num(v[8]),open:num(v[9]),limit_up:num(v[10]),limit_down:num(v[11]),name:v[37],amplitude:num(v[38]),high:num(v[39]),low:num(v[40]),volume:num(v[41]),amount:num(v[42])})}
async function gr(a:any){const code=String(a?.code||"");if(!/^\d+$/.test(code))throw new Error("code required");const raw=await listRaw(`CON_SO_${code}`);if(raw.length<16)throw new Error("option greeks payload too short");const v=[raw[0],...raw.slice(4)];return wrap({source:"sina",code,name:v[0],volume:num(v[1]),delta:num(v[2]),gamma:num(v[3]),theta:num(v[4]),vega:num(v[5]),iv:num(v[6]),high:num(v[7]),low:num(v[8]),trade_code:v[9],strike:num(v[10]),last:num(v[11]),theory:num(v[12])})}
const TOOLS=[{name:"option_codes_sina",description:"ETF option contract codes by month. Supports 50ETF/300ETF/STAR50ETF/500ETF.",inputSchema:{type:"object",properties:{underlying:{type:"string",enum:["510050","510300","588000","510500"]},call:{type:"boolean"}},additionalProperties:false}},{name:"option_tquote_sina",description:"ETF option T-quote with bid/ask, OI, strike, volume and amount.",inputSchema:{type:"object",properties:{code:{type:"string"}},required:["code"],additionalProperties:false}},{name:"option_greeks_sina",description:"ETF option Greeks and implied volatility.",inputSchema:{type:"object",properties:{code:{type:"string"}},required:["code"],additionalProperties:false}}];
Deno.serve(async(req)=>{if(req.method==="GET")return new Response(JSON.stringify({name:"stock-info-options",version:VERSION,status:"ok"}),{headers:{"content-type":"application/json"}});if(req.method!=="POST")return new Response("Method Not Allowed",{status:405});try{if((req.headers.get("authorization")||"")!==`Bearer ${await token()}`)return je(null,-32001,"Unauthorized",undefined,401);const b=await req.json(),id=b?.id,m=b?.method,p=b?.params||{};if(m==="initialize")return jr(id,{protocolVersion:PROTOCOL,capabilities:{tools:{}},serverInfo:{name:"stock-info-options",version:VERSION}});if(m==="notifications/initialized")return new Response(null,{status:202});if(m==="ping")return jr(id,{});if(m==="tools/list")return jr(id,{tools:TOOLS});if(m==="tools/call"){const n=String(p?.name||""),a=p?.arguments||{};if(n==="option_codes_sina")return jr(id,await codes(a));if(n==="option_tquote_sina")return jr(id,await tq(a));if(n==="option_greeks_sina")return jr(id,await gr(a));return je(id,-32601,`unknown tool ${n}`)}return je(id,-32601,`Method not found: ${m}`)}catch(e){return je(null,-32603,"Internal error",e instanceof Error?e.message:String(e),500)}});